name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Solo se activa cuando se hace push a la rama 'main'
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usa la versión de Node.js que prefieras

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Directorio donde se encuentran los archivos estáticos generados por Astro
          publish_branch: gh-pages  # GitHub Pages usa la rama 'gh-pages' para el despliegue